# Basic Python

## 1. Split this string

In [ ]:
s="Hi there Sam!"
s=s.split()
print(s);


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,{'tricky':['oh','man',{'target':[1,2,'hello']}]}]}

In [ ]:
d['k1'][2]['tricky'][2]['target'][2]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:",array)


An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)*30
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[30. 30. 30. 30. 30. 30. 30. 30. 30. 30.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
 import numpy as np
 x=np.arange(0,9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame ({})
print(df)

Empty DataFrame
Columns: []
Index: []


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
input = ['01/01/2023', '10/02/2023']
 
format = '%d/%m/%Y'
for i in input:
   
    print(datetime.datetime.strptime(i, format).date())

2023-01-01
2023-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns = ['S.No', 'Name','No'])
print(df)

   S.No Name  No
0     1  aaa  22
1     2  bbb  25
2     3  ccc  24
